### ISSUE TITLE
[feat] 테트리스 게임 기능 고도화

### ISSUE THREAD

**Issue by zvvony** [TeamS2-ICCAS2024/zen#1]
## 📌  Feature Issue
테트리스 게임 기능을 고도화하고, 전체적인 디자인을 수정한다. 

## 📝  To-do
- [x] 테트리스 게임 종료 후 보여지는 게임 종료 스크린 구현 (게임 결과 제공)
- [x] 테트리스 게임 화면 하단에 replay, quit 버튼 구현 
- [x] 테트리스 게임 화면 디자인 수정 (어플 분위기에 맞춰 수정)
