### ISSUE TITLE
[fix] 테트리스 방해요소 로직 오류 해결 및 알림 UI 고도화 

### ISSUE THREAD

**Issue by JunHyukYang** [TeamS2-ICCAS2024/zen#12]
## 📌  Feature Issue

방해요소 알림 UI 고도화 구현 할 예정입니다.

## 📝  To-do
<!— 해야 할 일들을 적어주세요. —>
- [x] 방해요소를 시각화할 수 있는 이미지 추가 작업
- [x] Text 수정 작업
- [x] 방해요소 주기 수정
- [x] 테트리스 replay, reset 실행 시 방해요소가 작동안하는 오류 해결
