### ISSUE TITLE
[refactor] 요가 게임 고도화  

### ISSUE THREAD

**Issue by zvvony** [TeamS2-ICCAS2024/zen#14]
## 📌  Feature Issue

요가 게임을 고도화한다. 

## 📝  To-do

- [x] 요가 포즈 목록 변경에 따른 새로운 모델 추가 
- [x] 요가 게임 종료 화면 로직 수정 (실제 게임 결과 반영)
- [x] 요가 게임 타이머 동작 로직 오류 수정 
- [x] 요가 게임 화면 하단의 leaf 로직 수정
