### ISSUE TITLE
[feat] 자가진단 레포트 UI 구현

### ISSUE THREAD

**Issue by JunHyukYang** [TeamS2-ICCAS2024/zen#32]
## 📌  Feature Issue

자가진단 레포트 UI 구현할 예정입니다.
## 📝  To-do

- [x] 자가진단 survey 페이지 구현
- [x] 자가진단 결과 페이지 구현
- [x] 결과 로직 구현
