### ISSUE TITLE
[feat] 배경 변경 기능 추가

### ISSUE THREAD

**Issue by Steven0914** [TeamS2-ICCAS2024/zen#36]
## 📝  To-do

- [ ] 캐릭터 메인 화면에서 배경 자동 변경되게 구현
- [ ] 캐릭터 콜렉션 화면에서 리프 갯수에 맞게 배경이 나오도록 구현
- [ ] 캐릭터 콜렉션에서 배경을 선택할 수 있도록 구현
