### ISSUE TITLE
[feat] Retrofit 모듈화 

### ISSUE THREAD

**Issue by zvvony** [TeamS2-ICCAS2024/zen#38]
## 📌  Feature Issue

통신을 위한 Retrofit 모듈화 

## 📝  To-do

- [x] RetrofitInstance 객체를 통해 여러 API 인터페이스 분리
- [x] 도메인 별 API 인터페이스 정의 (우선적으로 auth, user 도메인 구현)
- [x] 로그인 api 연결 
- [x] user 도메인 api 수정 (기존 연결되어 있는 상태)
