### ISSUE TITLE
[feat] 자가 진단 관련 기능 구현

### ISSUE THREAD

**Issue by Steven0914** [TeamS2-ICCAS2024/zen#48]
## 📌  Feature Issue

자가 진단 관련 기능을 구현합니다.

## 📝  To-do

- [ ] 기존의 뷰 네비게이션 로직 변경
- [ ] 자가 진단 페이지 구성
- [ ] 자가 진단 결과 화면 구성
