### ISSUE TITLE
[feat] 테트리스 게임 결과 리스트 조회 api 연결 

### ISSUE THREAD

**Issue by zvvony** [TeamS2-ICCAS2024/zen#66]
## 📌  Feature Issue

테트리스 게임 결과 리스트 조회 api 연결 

## 📝  To-do

- [x] 테트리스 게임 결과 리스트 조회 api 연결 
- [x] 테트리스 게임 결과 리스트 조회 페이지 리펙토링
- [x] 온보딩, 자가진단 페이지 리펙토링
