### ISSUE TITLE
[refactor] 전체적인 UI 리펙토링 

### ISSUE THREAD

**Issue by zvvony** [TeamS2-ICCAS2024/zen#75]
## 📌  Feature Issue

전체적인 UI 리펙토링 

## 📝  To-do

- [x] onBoarding 소개란에서 글자가 배경을 벗어나는 오류 수정 
- [x] navbar 아이콘 크기 맞추기 (크기와 두께가 다른 상태)
- [x] char_main 스크린 UI 조정 (setting 아이콘을 위로 올려서 비율 맞추기)
- [x] collection 스크린에서 캐릭터 별 background 맞춰주기
