### ISSUE TITLE
[refactor] 전체적인 UI 리펙토링 (for demo video)

### ISSUE THREAD

**Issue by zvvony** [TeamS2-ICCAS2024/zen#78]
## 📌  Feature Issue

전체적인 UI 리펙토링

## 📝  To-do

- [x] chat 스크린 UI 조정
- [x] 자가진단 report 스크린 UI 조정
- [x] welcome 스크린에서 구글로그인 버튼 빼기 (현재 기능 구현 x)
- [x] 일기 리스트 UI 수정하기
- [x] 테트리스 방해요소 UI 조정
- [ ] 심박 상승 시, 글씨를 빨간색으로 변경 
- [ ] 일기 기록에서 당시 함께한 챗봇 반영
- [x] 리포트 상단바 조정
- [ ] 자가진단 테스트 스크린 UI 조정
- [ ] userId 반영
